services:
  - type: web
    name: sha-bot-api
    env: python
    buildCommand: pip install -r requirements.txt && python scripts/prepare_render_deployment.py && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: .
      - key: LOG_LEVEL
        value: INFO
      - key: ALLOWED_ORIGINS
        value: "*"
    autoDeploy: true
    disk:
      name: sha-bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 